//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PopUp_Researcher.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BasicResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BasicResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PopUp_Researcher.Resources.BasicResources", typeof(BasicResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are You Sure?.
        /// </summary>
        internal static string AreYouSureQ {
            get {
                return ResourceManager.GetString("AreYouSureQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Survey Type.
        /// </summary>
        internal static string ChangeSurveyTypeQ {
            get {
                return ResourceManager.GetString("ChangeSurveyTypeQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\\IMAGES\\qMark.png.
        /// </summary>
        internal static string DeafultImagePath {
            get {
                return ResourceManager.GetString("DeafultImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit bRMS experiment is not supported at this moment.
        /// </summary>
        internal static string EditBrmsInvalid {
            get {
                return ResourceManager.GetString("EditBrmsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save an Experiment File.
        /// </summary>
        internal static string ExperimentDialogTitle {
            get {
                return ResourceManager.GetString("ExperimentDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experiment JSON|*.json.
        /// </summary>
        internal static string ExperimentFilter {
            get {
                return ResourceManager.GetString("ExperimentFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string ImageButtonText {
            get {
                return ResourceManager.GetString("ImageButtonText", resourceCulture);
            }
        }
    }
}
